[package]
name = "numov"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matroska = "0.26.1"
rusqlite = { version = "0.31.0", features = ["bundled"] }
walkdir = "2.4.0"
xxhash-rust = { version = "0.8.10", features = ["const_xxh32"] }
